version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: smartpark-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: smartpark
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d smartpark"]
      interval: 5s
      timeout: 5s
      retries: 5

  servicio-usuarios:
    build: ./servicio-usuarios
    container_name: smartpark-usuarios
    environment:
      - DATABASE_URL=postgresql://admin:superpassword123@db:5432/smartpark
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy

  servicio-taquilla:
    build: ./servicio-taquilla
    container_name: smartpark-taquilla
    environment:
      - DATABASE_URL=postgresql://admin:superpassword123@db:5432/smartpark
    ports:
      - "8002:8000"
    depends_on:
      db:
        condition: service_healthy

  # --- NUEVO SERVICIO FRONTEND ---
  servicio-frontend:
    build: ./servicio-frontend
    container_name: smartpark-frontend
    ports:
      - "5173:5173"
    volumes:
      # Sincroniza tu código local con el contenedor para ver cambios en tiempo real
      - ./servicio-frontend:/app
      # Evita que tu entorno local sobreescriba los módulos de Node dentro del contenedor
      - /app/node_modules
    depends_on:
      - servicio-usuarios
      - servicio-taquilla

volumes:
  db_data: